services:
  streamlit:
    build: ./streamlit
    container_name: streamlit_app
    ports:
      - "8501:8501"
    environment:
      ACNE_API_URL: http://acne:8000/predict
      OILY_API_URL: http://oily:8000/predict
      PRODUCT_API_URL: http://product:8000/recommend
    depends_on:
      - acne
      - oily
      - product

  acne:
    build: ./acne
    container_name: acne_api
    ports:
      - "8001:8000"

  oily:
    build: ./oily
    container_name: oily_api
    ports:
      - "8002:8000"

  product:
    build: ./product
    container_name: product_api
    ports:
      - "8003:8000"
    env_file:
      - .env
    volumes:
      - chroma_db:/app/chroma_db

volumes:
  chroma_db: