FRENCH_BRANDS = {
    "vichy",
    "la roche-posay",
    "la roche posay",
    "bioderma",
    "avène",
    "avene",
    "eau thermale avène",
    "eau thermale avene",
    "caudalie",
    "nuxe",
    "clarins",
    "lancôme",
    "lancome",
    "l'oréal",
    "l'oreal",
    "loreal",
    "garnier",
    "yves rocher",
    "yves saint laurent",
    "ysl beauté",
    "institut esthederm",
    "esthederm",
    "sothys",
    "filorga",
    "embryolisse",
    "lierac",
    "liérac",
    "roc",
    "roger & gallet",
    "sisley",
    "givenchy",
    "christian dior",
    "dior",
    "chanel",
    "guerlain",
    "payot",
    "biotherm",
    "mustela",
    "galénic",
    "galenic",
    "phyto",
    "kérastase",
    "kerastase",
    "decléor",
    "decleor",
    "svr",
    "a-derma",
    "aderma",
    "ducray",
    "klorane",
    "rené furterer",
    "rene furterer",
    "nuxuriance",
    "by terry",
    "make up for ever",
    "sephora collection",
    "erborian",
}


def is_french(brand: str) -> bool:
    if not brand or not isinstance(brand, str):
        return False
    return brand.lower().strip() in FRENCH_BRANDS
